// This file is automatically generated. Do not edit it directly.
// (Actually we are modifying it to support a beautiful, zero-config mock database fallback)
import { createClient } from "@supabase/supabase-js";
import { createServerFn } from "@tanstack/react-start";
import type { Database } from "./types";

// Server function that performs query operations on the local JSON database (menu_store.json)
export const handleMockQuery = createServerFn({ method: "POST" })
  .inputValidator((input: any) => input)
  .handler(async ({ data }) => {
    try {
      const {
        getCategories,
        getItems,
        upsertCategory,
        deleteCategory,
        upsertItem,
        deleteItem,
        toggleItemAvailable,
      } = await import("@/lib/local-db");

      const { action, table, payload, eq } = data;

      if (action === "select") {
        if (table === "menu_categories") {
          const cats = getCategories();
          return { data: cats, error: null };
        } else if (table === "menu_items") {
          let items = getItems();
          if (eq) {
            if (eq.field === "available") {
              items = items.filter((i) => i.available === eq.value);
            }
            if (eq.field === "category_id") {
              items = items.filter((i) => i.category_id === eq.value);
            }
            if (eq.field === "id") {
              items = items.filter((i) => i.id === eq.value);
            }
          }
          return { data: items, error: null };
        }
        return { data: [], error: null };
      }

      if (action === "insert") {
        if (table === "menu_categories") {
          const res = upsertCategory(payload);
          return { data: res, error: null };
        } else if (table === "menu_items") {
          const res = upsertItem(payload);
          return { data: res, error: null };
        }
      }

      if (action === "update") {
        if (table === "menu_categories") {
          const res = upsertCategory({ ...payload, id: eq?.value });
          return { data: res, error: null };
        } else if (table === "menu_items") {
          const res = upsertItem({ ...payload, id: eq?.value });
          return { data: res, error: null };
        }
      }

      if (action === "delete") {
        if (table === "menu_categories") {
          const res = deleteCategory(eq?.value);
          return { data: res, error: null };
        } else if (table === "menu_items") {
          const res = deleteItem(eq?.value);
          return { data: res, error: null };
        }
      }

      return { data: null, error: { message: `Unsupported mock action: ${action}` } };
    } catch (err: any) {
      console.error("Mock query error:", err);
      return { data: null, error: { message: err.message || "Mock DB error" } };
    }
  });

// A robust query builder that mimics standard Supabase database chainable API
class MockQueryBuilder {
  private query: {
    action: string;
    table: string;
    payload?: any;
    eq?: { field: string; value: any };
    order?: string;
    single?: boolean;
    maybeSingle?: boolean;
  };

  constructor(table: string, action: string = "select", payload?: any) {
    this.query = { table, action, payload };
  }

  select(fields?: string) {
    return this;
  }

  eq(field: string, value: any) {
    this.query.eq = { field, value };
    return this;
  }

  order(field: string) {
    this.query.order = field;
    return this;
  }

  single() {
    this.query.single = true;
    return this;
  }

  maybeSingle() {
    this.query.maybeSingle = true;
    return this;
  }

  async execute() {
    const res = await handleMockQuery({ data: this.query });
    if (this.query.single || this.query.maybeSingle) {
      const data = Array.isArray(res.data) ? res.data[0] : res.data;
      return { data: data ?? null, error: res.error };
    }
    return res;
  }

  then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

// Complete mock client definition
const mockSupabase = {
  from: (table: string) => {
    return {
      select: (fields?: string) => new MockQueryBuilder(table, "select"),
      insert: (payload: any) => new MockQueryBuilder(table, "insert", payload),
      update: (payload: any) => new MockQueryBuilder(table, "update", payload),
      delete: () => new MockQueryBuilder(table, "delete"),
    };
  },
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  },
  channel: (name: string) => {
    return {
      on: (event: string, filter: any, callback: any) => {
        return {
          subscribe: () => {
            // Setup poller to periodically trigger updates
            const interval = setInterval(() => {
              callback({ event: "UPDATE", new: {} });
            }, 4000);
            return {
              unsubscribe: () => clearInterval(interval),
            };
          },
        };
      },
      subscribe: () => {
        return {
          unsubscribe: () => {},
        };
      },
    };
  },
  removeChannel: (channel: any) => {
    if (channel && typeof channel.unsubscribe === "function") {
      channel.unsubscribe();
    }
  },
};

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Missing environment variables. Using high-fidelity JSON-database mock client instead.",
    );
    return mockSupabase as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
